const fontsToLoad = [
  { family: 'Roboto', style: 'Regular' },
  { family: 'Roboto', style: 'Bold' },
  { family: 'Josefin Sans', style: 'Regular' },
  { family: 'Josefin Sans', style: 'Bold' },
  { family: 'Abril Fatface', style: 'Regular' },
  { family: 'Alegreya', style: 'Regular' },
  { family: 'Alegreya', style: 'Bold' },
  { family: 'Archivo', style: 'Regular' },
  { family: 'Archivo', style: 'Bold' },
  { family: 'Bitter', style: 'Regular' },
  { family: 'Bitter', style: 'Bold' },
  { family: 'Cabin', style: 'Regular' },
  { family: 'Cabin', style: 'Bold' },
  { family: 'Cardo', style: 'Regular' },
  { family: 'Cardo', style: 'Bold' },
  { family: 'Domine', style: 'Regular' },
  { family: 'Domine', style: 'Bold' },
  { family: 'Fira Mono', style: 'Regular' },
  { family: 'Fira Mono', style: 'Bold' },
  { family: 'Fira Sans', style: 'Regular' },
  { family: 'Fira Sans', style: 'Bold' },
  { family: 'Karla', style: 'Regular' },
  { family: 'Karla', style: 'Bold' },
  { family: 'Kreon', style: 'Regular' },
  { family: 'Kreon', style: 'Bold' },
  { family: 'Lato', style: 'Regular' },
  { family: 'Lato', style: 'Bold' },
  { family: 'Lora', style: 'Regular' },
  { family: 'Lora', style: 'Bold' },
  { family: 'Merriweather', style: 'Regular' },
  { family: 'Merriweather', style: 'Bold' },
  { family: 'Montserrat', style: 'Regular' },
  { family: 'Montserrat', style: 'Bold' },
  { family: 'Nunito', style: 'Regular' },
  { family: 'Nunito', style: 'Bold' },
  { family: 'Open Sans', style: 'Regular' },
  { family: 'Open Sans', style: 'Bold' },
  { family: 'Playfair Display', style: 'Regular' },
  { family: 'Playfair Display', style: 'Bold' },
  { family: 'Prompt', style: 'Regular' },
  { family: 'Prompt', style: 'Bold' },
  { family: 'PT Sans', style: 'Regular' },
  { family: 'PT Sans', style: 'Bold' },
  { family: 'Raleway', style: 'Regular' },
  { family: 'Raleway', style: 'Bold' },
  { family: 'Roboto', style: 'Regular' },
  { family: 'Roboto', style: 'Bold' },
  { family: 'Rokkitt', style: 'Regular' },
  { family: 'Rokkitt', style: 'Bold' },
  { family: 'Source Sans Pro', style: 'Regular' },
  { family: 'Source Sans Pro', style: 'Bold' },
  { family: 'Space Mono', style: 'Regular' },
  { family: 'Space Mono', style: 'Bold' },
  { family: 'Ubuntu', style: 'Regular' },
  { family: 'Ubuntu', style: 'Bold' },
  { family: 'Yeseva One', style: 'Regular' }
]

export { fontsToLoad }
